### ISSUE TITLE
Frameworks e libs utilizados no desafio

### ISSUE THREAD

**Issue by patrick-narciso** [hurbcom/challenge-charlie#14]
Pode ser utilizado um framework javascript no desafio, como vue.js por exemplo, ou somente jQuery? E quanto a pré-processador CSS, pode ser utilizado SASS ou somente LESS?

**Comment by renatoelias** [comment]
@patrick-narciso :) use o que seu coração mandar

**Comment by renatoelias** [comment]
@patrick-narciso porem lembrando o readme:

```
Você pode utilizar jQuery mas não pode usar nenhum plugin de jQuery, queremos ver o seu trabalho. Para a folha de estilo, deve ser utilizado LESS.
```

**Comment by patrick-narciso** [comment]
@renatoelias sim, a minha dúvida é justamente quanto a isso. Então, na prática posso utilizar SASS e Vue.Js certo?

**Comment by bernardolm** [comment]
Olá @patrick-narciso, tudo bem?
Quanto ao pré-processador, pelas instruções só o LESS poderá ser utilizado.
Abraço e bom desafio!

**Comment by patrick-narciso** [comment]
opa, ok então @ruanmer , obrigado pelos esclarecimentos :)

**Comment by bernardolm** [comment]
@patrick-narciso, o que o @ruanmer diz, eu assino embaixo. Mete bronca!

**Comment by zanaca** [comment]
Thank you! Your code is being reviewed.
