### ISSUE TITLE
Url de consulta do Yahoo mudou

### ISSUE THREAD

**Issue by vinnycl** [hurbcom/challenge-charlie#26]
Em 3 de Janeiro de 2019, weather.yahooapis.com e query.yahooapis.com foram desativadas.

**A nova URL é:**
https://weather-ydn-yql.media.yahoo.com/forecastrss

**Para acessar a resposta, é necessário autenticação com uma chave e identificação de aplicativo obtido pelo link:**
https://developer.yahoo.com/apps/create/

**Pode demorar de algumas horas até 3 úteis dia para adicionar a aplicação a uma Whitelist:**
https://goo.gl/forms/ixXUBJ00xMQc5ne23

**Para enviar o Header correto, é necessário seguir a documentação completa:**
https://developer.yahoo.com/weather/documentation.html

**Comment by zanaca** [comment]
Thank you! Your code is being reviewed.
