### ISSUE TITLE
Cor das temperaturas em ºF

### ISSUE THREAD

**Issue by AvnerGeraldo** [hurbcom/challenge-charlie#42]
Qual cor devo aplicar quando as temperaturas estiverem em ºF ?

**Comment by pedrobslisboa** [comment]
As cores devem seguir o padrão da unidade ºC:
> Para temperaturas abaixo de 15ºC deve ser usado tons de azul, para temperaturas acima de 35ºC

A unica coisa que deve ser alterada é o valor da temperatura e sua unidade na mudança de ºC para ºF

**Comment by AvnerGeraldo** [comment]
tudo bem, obrigado!
