### ISSUE TITLE
json correto?

### ISSUE THREAD

**Issue by angelofmfonseca** [hurbcom/challenge-charlie#43]
Os JSON do desafio Charlie estão corretos?

**Comment by ruanmer** [comment]
@angelofmfonseca está falando da URL do OpenWeather? Se for isso, é só trocar na URL `{{location_name}}` pela localidade desejada. Ex: http://api.openweathermap.org/data/2.5/weather?q=Rio%20de%20Janeiro&APPID=7ba73e0eb8efe773ed08bfd0627f07b8
