### ISSUE TITLE
API de previsão do tempo

### ISSUE THREAD

**Issue by fernandogatto** [hurbcom/challenge-charlie#61]
O link da API de previsão do tempo no README só busca a previsão do dia atual.

Segue abaixo um exemplo com a relação de 'hoje', 'amanhã' e 'depois de amanhã':

```
http://api.openweathermap.org/data/2.5/forecast/daily?q={cidade}&APPID={aapid}&cnt=3
```

**Comment by ruanmer** [comment]
@fernandogatto Não vem um array de dias na prop `list`? Veja a docs https://openweathermap.org/forecast16

**Comment by fernandogatto** [comment]
Vem sim, tudo certo. Só a url que está no README me direciona para um caminho ```.../data/2.5/weather?...``` e não ```/forecast/daily?```, entendeu? É mais um aviso mesmo, caso alguém fique nessa dúvida.

**Comment by ruanmer** [comment]
@fernandogatto ah entendi.. achei que era uma dúvida. Vamos verificar. Obrigado.

**Comment by MarcioAntonioRodrigues** [comment]
Não consigo trazer a previsão do 'hoje', 'amanhã' e 'depois de amanhã' utilizando a url http://api.openweathermap.org/data/2.5/forecast/daily?q={cidade}&APPID={aapid}&cnt=3

Parece que só é possível com contas pagas... Como proceder?

**Comment by ruanmer** [comment]
@MarcioAntonioRodrigues usa a URL http://api.openweathermap.org/data/2.5/weather?q={cidade}&appid={appid}
