### ISSUE TITLE
API previsão do tempo para 'hoje', 'amanhã' e 'depois de amanhã' só está permitida para contas pagas

### ISSUE THREAD

**Issue by MarcioAntonioRodrigues** [hurbcom/challenge-charlie#78]
Não consigo trazer a previsão do 'hoje', 'amanhã' e 'depois de amanhã' utilizando a url http://api.openweathermap.org/data/2.5/forecast/daily?q={cidade}&APPID={aapid}&cnt=3

Parece que só é possível com contas pagas... Como proceder?

**Comment by ruanmer** [comment]
@MarcioAntonioRodrigues usa a URL http://api.openweathermap.org/data/2.5/weather?q={cidade}&appid={appid}

**Comment by MarcioAntonioRodrigues** [comment]
Esta URL só retorna a previsão do dia atual...

**Comment by ruanmer** [comment]
@MarcioAntonioRodrigues usa as coordenadas em https://openweathermap.org/api/one-call-api

**Comment by vfernandes0408** [comment]
Estou com o problema parecido. Quando crio uma conta nova ela não da acesso ao one-call-api pois só está disponível no plano pago.
{
    "cod": 429,
    "message": "Your account is temporary blocked due to exceeding of requests limitation of your subscription type. Please choose the proper subscription http://openweathermap.org/price"
}
