### ISSUE TITLE
[Issue] Api do Openweather

### ISSUE THREAD

**Issue by vfernandes0408** [hurbcom/challenge-charlie#85]
Pessoal boa tarde.
Estou com problema com a api de one-call do Open Weather. Estou recebendo a seguinte mensagem abaixo. Fiz a criação de uma conta nova porem para para acessar esse endpoint ele é exclusivo na conta paga.

```
{
    "cod": 429,
    "message": "Your account is temporary blocked due to exceeding of requests limitation of your subscription type. Please choose the proper subscription http://openweathermap.org/price"
}
```

**Comment by ruanmer** [comment]
@vfernandes0408 conseguiu resolver o problema?

**Comment by vfernandes0408** [comment]
Consegui. Depois de um tempo ela já voltou a funcionar
